"""Added Name to Note

Revision ID: 844666c4a6c7
Revises: 44f1fa7c8d37
Create Date: 2022-07-04 15:54:33.691320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844666c4a6c7'
down_revision = '44f1fa7c8d37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('Name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Note', 'Name')
    # ### end Alembic commands ###
