"""wtf3

Revision ID: 4fb4d8ac510f
Revises: 71b8b695781c
Create Date: 2022-06-30 11:36:29.870968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fb4d8ac510f'
down_revision = '71b8b695781c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
