"""wtf2

Revision ID: 71b8b695781c
Revises: 8a38f6cc1acc
Create Date: 2022-06-30 11:35:39.484299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b8b695781c'
down_revision = '8a38f6cc1acc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
