"""added column to company

Revision ID: 870ed64ec687
Revises: 73082a4dbe88
Create Date: 2022-06-30 11:29:53.340350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870ed64ec687'
down_revision = '73082a4dbe88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_NewsArticle_ArticleId', table_name='NewsArticle')
    op.drop_table('NewsArticle')
    op.drop_index('ix_StockHolder_StockHolderId', table_name='StockHolder')
    op.drop_table('StockHolder')
    op.drop_index('ix_Note_NoteId', table_name='Note')
    op.drop_table('Note')
    op.drop_index('ix_CapitalRaise_RaiseId', table_name='CapitalRaise')
    op.drop_table('CapitalRaise')
    op.drop_index('ix_Aid_AidId', table_name='Aid')
    op.drop_table('Aid')
    op.drop_index('ix_Company_OrgNumber', table_name='Company')
    op.drop_table('Company')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('OrgNumber', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('CompanyName', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Email', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Sector', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Employees', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Municipality', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('HomePage', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('OrgNumber', name='PK__Company__00375EACA3C4DBC1')
    )
    op.create_index('ix_Company_OrgNumber', 'Company', ['OrgNumber'], unique=False)
    op.create_table('Aid',
    sa.Column('AidId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('GivenBy', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Type', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Reason', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('County', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('DateGiven', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('OrgNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], name='FK__Aid__OrgNumber__19DFD96B'),
    sa.PrimaryKeyConstraint('AidId', name='PK__Aid__1098675EB43501B5')
    )
    op.create_index('ix_Aid_AidId', 'Aid', ['AidId'], unique=False)
    op.create_table('CapitalRaise',
    sa.Column('RaiseId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Sum', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Link', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('OrgNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], name='FK__CapitalRa__OrgNu__1CBC4616'),
    sa.PrimaryKeyConstraint('RaiseId', name='PK__CapitalR__FF74BABE15823F5D')
    )
    op.create_index('ix_CapitalRaise_RaiseId', 'CapitalRaise', ['RaiseId'], unique=False)
    op.create_table('Note',
    sa.Column('NoteId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Note', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OrgNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], name='FK__Note__OrgNumber__114A936A'),
    sa.PrimaryKeyConstraint('NoteId', name='PK__Note__EACE355F1A6AA758')
    )
    op.create_index('ix_Note_NoteId', 'Note', ['NoteId'], unique=False)
    op.create_table('StockHolder',
    sa.Column('StockHolderId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OrgNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], name='FK__StockHold__OrgNu__17036CC0'),
    sa.PrimaryKeyConstraint('StockHolderId', name='PK__StockHol__7C8AB68CF56A7CF9')
    )
    op.create_index('ix_StockHolder_StockHolderId', 'StockHolder', ['StockHolderId'], unique=False)
    op.create_table('NewsArticle',
    sa.Column('ArticleId', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('URL', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('Title', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('OrgNumber', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], name='FK__NewsArtic__OrgNu__14270015'),
    sa.PrimaryKeyConstraint('ArticleId', name='PK__NewsArti__9C6270E850F2AA4D')
    )
    op.create_index('ix_NewsArticle_ArticleId', 'NewsArticle', ['ArticleId'], unique=False)
    # ### end Alembic commands ###
