"""wtf5

Revision ID: 8758b9b57384
Revises: 4fb4d8ac510f
Create Date: 2022-06-30 11:51:54.201878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8758b9b57384'
down_revision = '4fb4d8ac510f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Company',
    sa.Column('OrgNumber', sa.Integer(), nullable=False),
    sa.Column('CompanyName', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Sector', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Employees', sa.Integer(), nullable=True),
    sa.Column('Municipality', sa.String(), nullable=True),
    sa.Column('HomePage', sa.String(), nullable=True),
    sa.Column('test', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('OrgNumber')
    )
    op.create_index(op.f('ix_Company_OrgNumber'), 'Company', ['OrgNumber'], unique=False)
    op.create_table('Aid',
    sa.Column('AidId', sa.String(length=100), nullable=False),
    sa.Column('Sum', sa.Integer(), nullable=True),
    sa.Column('GivenBy', sa.String(), nullable=True),
    sa.Column('Type', sa.String(), nullable=True),
    sa.Column('Reason', sa.String(), nullable=True),
    sa.Column('County', sa.String(), nullable=True),
    sa.Column('DateGiven', sa.Date(), nullable=True),
    sa.Column('OrgNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], ),
    sa.PrimaryKeyConstraint('AidId')
    )
    op.create_index(op.f('ix_Aid_AidId'), 'Aid', ['AidId'], unique=False)
    op.create_table('CapitalRaise',
    sa.Column('RaiseId', sa.Integer(), nullable=False),
    sa.Column('Sum', sa.Integer(), nullable=True),
    sa.Column('Link', sa.String(), nullable=True),
    sa.Column('Date', sa.Date(), nullable=True),
    sa.Column('OrgNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], ),
    sa.PrimaryKeyConstraint('RaiseId')
    )
    op.create_index(op.f('ix_CapitalRaise_RaiseId'), 'CapitalRaise', ['RaiseId'], unique=False)
    op.create_table('NewsArticle',
    sa.Column('ArticleId', sa.Integer(), nullable=False),
    sa.Column('URL', sa.String(), nullable=True),
    sa.Column('Title', sa.String(), nullable=True),
    sa.Column('OrgNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], ),
    sa.PrimaryKeyConstraint('ArticleId')
    )
    op.create_index(op.f('ix_NewsArticle_ArticleId'), 'NewsArticle', ['ArticleId'], unique=False)
    op.create_table('Note',
    sa.Column('NoteId', sa.Integer(), nullable=False),
    sa.Column('Note', sa.String(), nullable=True),
    sa.Column('OrgNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], ),
    sa.PrimaryKeyConstraint('NoteId')
    )
    op.create_index(op.f('ix_Note_NoteId'), 'Note', ['NoteId'], unique=False)
    op.create_table('StockHolder',
    sa.Column('StockHolderId', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('OrgNumber', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['OrgNumber'], ['Company.OrgNumber'], ),
    sa.PrimaryKeyConstraint('StockHolderId')
    )
    op.create_index(op.f('ix_StockHolder_StockHolderId'), 'StockHolder', ['StockHolderId'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_StockHolder_StockHolderId'), table_name='StockHolder')
    op.drop_table('StockHolder')
    op.drop_index(op.f('ix_Note_NoteId'), table_name='Note')
    op.drop_table('Note')
    op.drop_index(op.f('ix_NewsArticle_ArticleId'), table_name='NewsArticle')
    op.drop_table('NewsArticle')
    op.drop_index(op.f('ix_CapitalRaise_RaiseId'), table_name='CapitalRaise')
    op.drop_table('CapitalRaise')
    op.drop_index(op.f('ix_Aid_AidId'), table_name='Aid')
    op.drop_table('Aid')
    op.drop_index(op.f('ix_Company_OrgNumber'), table_name='Company')
    op.drop_table('Company')
    # ### end Alembic commands ###
