"""wtf

Revision ID: 8a38f6cc1acc
Revises: 870ed64ec687
Create Date: 2022-06-30 11:34:44.757056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a38f6cc1acc'
down_revision = '870ed64ec687'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
